/**
 * ====================================================================
 * CATÁLOGO DE PERFUMES — J'AIME CE PARFUM
 * ====================================================================
 * Contiene los 260 perfumes con sus casas y precios exactos.
 * Venta exclusiva al detal. Puedes modificar el precio de cada artículo.
 */

const PERFUMES_BASE = [
  {"id":"p001","casa":"Afnan","nombre":"9 AM Dive","precio":20},
  {"id":"p002","casa":"Afnan","nombre":"9 AM Pour Femme","precio":20},
  {"id":"p003","casa":"Afnan","nombre":"9 PM Elixir","precio":20},
  {"id":"p004","casa":"Afnan","nombre":"9 PM Men","precio":20},
  {"id":"p005","casa":"Afnan","nombre":"9 PM Night Out","precio":25},
  {"id":"p006","casa":"Afnan","nombre":"9 PM Pour Femme","precio":20},
  {"id":"p007","casa":"Afnan","nombre":"9 PM Rebel","precio":20},
  {"id":"p008","casa":"Al Haramain","nombre":"Amber Oud Aqua Dubai Edition","precio":20},
  {"id":"p009","casa":"Al Haramain","nombre":"Amber Oud Dubai Night","precio":20},
  {"id":"p010","casa":"Al Haramain","nombre":"Amber Oud Gold Edition","precio":20},
  {"id":"p011","casa":"Al Haramain","nombre":"Amber Oud Ultra Violet","precio":20},
  {"id":"p012","casa":"Antonio Banderas","nombre":"Blue Seduction","precio":18},
  {"id":"p013","casa":"Ariana Grande","nombre":"Ari","precio":18},
  {"id":"p014","casa":"Ariana Grande","nombre":"Cloud","precio":9},
  {"id":"p015","casa":"Ariana Grande","nombre":"Cloud Intense","precio":9},
  {"id":"p016","casa":"Ariana Grande","nombre":"Cloud Pink","precio":15},
  {"id":"p017","casa":"Ariana Grande","nombre":"Mod","precio":15},
  {"id":"p018","casa":"Ariana Grande","nombre":"Mod Blush","precio":15},
  {"id":"p019","casa":"Ariana Grande","nombre":"REM","precio":18},
  {"id":"p020","casa":"Ariana Grande","nombre":"Sweet Like Candy","precio":18},
  {"id":"p021","casa":"Ariana Grande","nombre":"Thank U Next","precio":15},
  {"id":"p022","casa":"Ariana Grande","nombre":"Thank U Next 2.0","precio":15},
  {"id":"p023","casa":"Armaf","nombre":"Caballo","precio":20},
  {"id":"p024","casa":"Armaf","nombre":"Club de Nuit Intense Man","precio":15},
  {"id":"p025","casa":"Armaf","nombre":"Club de Nuit Lionheart Men","precio":20},
  {"id":"p026","casa":"Armaf","nombre":"Club de Nuit Lionheart Woman","precio":20},
  {"id":"p027","casa":"Armaf","nombre":"Club de Nuit Oud","precio":15},
  {"id":"p028","casa":"Armaf","nombre":"Club de Nuit Milestone","precio":15},
  {"id":"p029","casa":"Armaf","nombre":"Club de Nuit Imperiale","precio":15},
  {"id":"p030","casa":"Armaf","nombre":"Club de Nuit Sillage","precio":15},
  {"id":"p031","casa":"Armaf","nombre":"Club de Nuit Untold","precio":15},
  {"id":"p032","casa":"Armaf","nombre":"Club de Nuit Maleka","precio":15},
  {"id":"p033","casa":"Armaf","nombre":"Club de Nuit Iconic","precio":15},
  {"id":"p034","casa":"Armaf","nombre":"Club de Nuit Urban Man Elixir","precio":15},
  {"id":"p035","casa":"Armaf","nombre":"Club de Nuit Woman","precio":15},
  {"id":"p036","casa":"Armaf","nombre":"Club de Nuit Precieux","precio":30},
  {"id":"p037","casa":"Armaf","nombre":"Island Bliss","precio":20},
  {"id":"p038","casa":"Armaf","nombre":"Island Breeze","precio":20},
  {"id":"p039","casa":"Armaf","nombre":"Bon Bon","precio":20},
  {"id":"p040","casa":"Armaf","nombre":"Odyssey AOUD","precio":15},
  {"id":"p041","casa":"Armaf","nombre":"Odyssey Aqua","precio":20},
  {"id":"p042","casa":"Armaf","nombre":"Odyssey Artisto","precio":15},
  {"id":"p043","casa":"Armaf","nombre":"Odyssey Bahamas","precio":20},
  {"id":"p044","casa":"Armaf","nombre":"Odyssey Candee","precio":15},
  {"id":"p045","casa":"Armaf","nombre":"Odyssey Dubai Chocolate","precio":20},
  {"id":"p046","casa":"Armaf","nombre":"Odyssey Homme","precio":15},
  {"id":"p047","casa":"Armaf","nombre":"Odyssey Homme White Edition","precio":15},
  {"id":"p048","casa":"Armaf","nombre":"Odyssey Limoni","precio":20},
  {"id":"p049","casa":"Armaf","nombre":"Odyssey Mandarin Sky","precio":20},
  {"id":"p050","casa":"Armaf","nombre":"Odyssey Mandarin Sky Elixir","precio":20},
  {"id":"p051","casa":"Armaf","nombre":"Odyssey Mandarin Sky Vintage","precio":20},
  {"id":"p052","casa":"Armaf","nombre":"Odyssey Marshmellow","precio":20},
  {"id":"p053","casa":"Armaf","nombre":"Odyssey Mega","precio":15},
  {"id":"p054","casa":"Armaf","nombre":"Odyssey Go Mango","precio":20},
  {"id":"p055","casa":"Armaf","nombre":"Odyssey Toffee Coffee","precio":20},
  {"id":"p056","casa":"Armaf","nombre":"Odyssey Spectra","precio":15},
  {"id":"p057","casa":"Armaf","nombre":"Odyssey Eau de Montagne","precio":20},
  {"id":"p058","casa":"Armaf","nombre":"Odyssey Tyrant","precio":15},
  {"id":"p059","casa":"Armaf","nombre":"Odyssey Wild One","precio":15},
  {"id":"p060","casa":"Armaf","nombre":"Yum Yum","precio":20},
  {"id":"p061","casa":"Azzaro","nombre":"Azzaro Wanted","precio":20},
  {"id":"p062","casa":"Azzaro","nombre":"Azzaro Intense","precio":20},
  {"id":"p063","casa":"Bharara","nombre":"Double Bleu","precio":20},
  {"id":"p064","casa":"Bharara","nombre":"King","precio":20},
  {"id":"p065","casa":"Bharara","nombre":"Niche Femme","precio":20},
  {"id":"p066","casa":"Bharara","nombre":"Onyx","precio":20},
  {"id":"p067","casa":"Bharara","nombre":"Rose","precio":20},
  {"id":"p068","casa":"Bharara","nombre":"Scarlett","precio":20},
  {"id":"p069","casa":"Bharara","nombre":"Soleil","precio":20},
  {"id":"p070","casa":"Britney Spears","nombre":"Fantasy","precio":15},
  {"id":"p071","casa":"Britney Spears","nombre":"Fantasy Anniversary","precio":15},
  {"id":"p072","casa":"Britney Spears","nombre":"Fantasy Midnight","precio":15},
  {"id":"p073","casa":"Calvin Klein","nombre":"Eternity","precio":15},
  {"id":"p074","casa":"Calvin Klein","nombre":"One","precio":15},
  {"id":"p075","casa":"Carolina Herrera","nombre":"212 Héroes Forever Young W","precio":15},
  {"id":"p076","casa":"Carolina Herrera","nombre":"212 Men Heroes Forever Young","precio":15},
  {"id":"p077","casa":"Carolina Herrera","nombre":"212 Men NYC","precio":15},
  {"id":"p078","casa":"Carolina Herrera","nombre":"212 VIP Black","precio":15},
  {"id":"p079","casa":"Carolina Herrera","nombre":"212 VIP Black I Love NY","precio":15},
  {"id":"p080","casa":"Carolina Herrera","nombre":"212 VIP Men","precio":15},
  {"id":"p081","casa":"Carolina Herrera","nombre":"212 VIP Rosé","precio":15},
  {"id":"p082","casa":"Carolina Herrera","nombre":"212 VIP Rosé NY","precio":15},
  {"id":"p083","casa":"Carolina Herrera","nombre":"Bad Boy","precio":15},
  {"id":"p084","casa":"Carolina Herrera","nombre":"CH","precio":15},
  {"id":"p085","casa":"Carolina Herrera","nombre":"Good Girl","precio":15},
  {"id":"p086","casa":"Carolina Herrera","nombre":"Good Girl Blush","precio":20},
  {"id":"p087","casa":"Carolina Herrera","nombre":"Good Girl Gold Fantasy","precio":15},
  {"id":"p088","casa":"Carolina Herrera","nombre":"Good Girl Fantastic Pink","precio":20},
  {"id":"p089","casa":"Carolina Herrera","nombre":"Good Girl Blush Elixir","precio":20},
  {"id":"p090","casa":"Carolina Herrera","nombre":"Good Girl Velvet Fatale","precio":15},
  {"id":"p091","casa":"Carolina Herrera","nombre":"La Bomba","precio":20},
  {"id":"p092","casa":"Carolina Herrera","nombre":"Very Good Girl","precio":15},
  {"id":"p093","casa":"Chanel","nombre":"Allure Homme Sport","precio":15},
  {"id":"p094","casa":"Chanel","nombre":"Bleu de Chanel","precio":15},
  {"id":"p095","casa":"Chanel","nombre":"Chance Eau Tendre","precio":15},
  {"id":"p096","casa":"Chanel","nombre":"Chanel No.5","precio":15},
  {"id":"p097","casa":"Chanel","nombre":"Coco Mademoiselle","precio":15},
  {"id":"p098","casa":"Christian Dior","nombre":"Miss Dior","precio":20},
  {"id":"p099","casa":"Christian Dior","nombre":"Sauvage","precio":18},
  {"id":"p100","casa":"Christian Dior","nombre":"Sauvage Elixir","precio":18},
  {"id":"p101","casa":"Creed","nombre":"Creed Aventus","precio":15},
  {"id":"p102","casa":"Creed","nombre":"Creed Silver Mountain Water","precio":15},
  {"id":"p103","casa":"Creed","nombre":"Creed Absolu Aventus","precio":15},
  {"id":"p104","casa":"Dolce \u0026 Gabbana","nombre":"Light Blue Pour Femme","precio":15},
  {"id":"p105","casa":"Dolce \u0026 Gabbana","nombre":"Light Blue Pour Homme","precio":15},
  {"id":"p106","casa":"Dolce \u0026 Gabbana","nombre":"Light Blue Love is Love W","precio":15},
  {"id":"p107","casa":"Dumont","nombre":"Nitro Red","precio":20},
  {"id":"p108","casa":"Escada","nombre":"Fairy Love","precio":9},
  {"id":"p109","casa":"Escada","nombre":"Sorbetto Rosso","precio":15},
  {"id":"p110","casa":"Ferrari","nombre":"Scuderia Ferrari Red","precio":15},
  {"id":"p111","casa":"French Avenue","nombre":"Vulcan Baie","precio":20},
  {"id":"p112","casa":"French Avenue","nombre":"Vulcan Feu","precio":20},
  {"id":"p113","casa":"French Avenue","nombre":"Vulcan Sable","precio":20},
  {"id":"p114","casa":"Giorgio Armani","nombre":"Acqua Di Gio (Normal)","precio":15},
  {"id":"p115","casa":"Giorgio Armani","nombre":"Acqua Di Gio Profumo","precio":15},
  {"id":"p116","casa":"Giorgio Armani","nombre":"Stronger With You","precio":20},
  {"id":"p117","casa":"Giorgio Armani","nombre":"Stronger With You Intensely","precio":20},
  {"id":"p118","casa":"Givenchy","nombre":"Pour Homme","precio":15},
  {"id":"p119","casa":"Hugo Boss","nombre":"Man","precio":15},
  {"id":"p120","casa":"Hugo Boss","nombre":"Intense","precio":15},
  {"id":"p121","casa":"Hugo Boss","nombre":"Jeans","precio":15},
  {"id":"p122","casa":"Hugo Boss","nombre":"Boss Bottled","precio":15},
  {"id":"p123","casa":"Hugo Boss","nombre":"Boss Bottled Infinite","precio":15},
  {"id":"p124","casa":"Hugo Boss","nombre":"Boss Bottled Night","precio":15},
  {"id":"p125","casa":"Hugo Boss","nombre":"Boss Bottled Marine","precio":15},
  {"id":"p126","casa":"Hugo Boss","nombre":"Boss Unlimited","precio":15},
  {"id":"p127","casa":"Hugo Boss","nombre":"Boss Bottled Absolu","precio":15},
  {"id":"p128","casa":"Hugo Boss","nombre":"Hugo Boss Parfum","precio":15},
  {"id":"p129","casa":"Hugo Boss","nombre":"The Scent Woman","precio":9},
  {"id":"p130","casa":"Issey Miyake","nombre":"L\u0027eau D\u0027issey pour Homme","precio":15},
  {"id":"p131","casa":"Jean Paul Gaultier","nombre":"Gaultier Divine","precio":20},
  {"id":"p132","casa":"Jean Paul Gaultier","nombre":"La Belle Paradise Garden","precio":20},
  {"id":"p133","casa":"Jean Paul Gaultier","nombre":"Le Male","precio":20},
  {"id":"p134","casa":"Jean Paul Gaultier","nombre":"Le Male Aviator","precio":20},
  {"id":"p135","casa":"Jean Paul Gaultier","nombre":"Le Male Le Parfum","precio":20},
  {"id":"p136","casa":"Jean Paul Gaultier","nombre":"Le Beau","precio":20},
  {"id":"p137","casa":"Jean Paul Gaultier","nombre":"Le Beau Le Parfum","precio":20},
  {"id":"p138","casa":"Jean Paul Gaultier","nombre":"Le Beau Paradise Garden","precio":20},
  {"id":"p139","casa":"Jean Paul Gaultier","nombre":"Le Male Elixir","precio":20},
  {"id":"p140","casa":"Jean Paul Gaultier","nombre":"Scandal Pour Femme","precio":20},
  {"id":"p141","casa":"Jean Paul Gaultier","nombre":"Scandal Pour Homme","precio":20},
  {"id":"p142","casa":"Jean Paul Gaultier","nombre":"Scandal Intense","precio":20},
  {"id":"p143","casa":"Jean Paul Gaultier","nombre":"Scandal Le Parfum","precio":20},
  {"id":"p144","casa":"Jean Paul Gaultier","nombre":"Ultra Male","precio":20},
  {"id":"p145","casa":"Katy Perry","nombre":"Purr","precio":15},
  {"id":"p146","casa":"Katy Perry","nombre":"Meow","precio":15},
  {"id":"p147","casa":"Lacoste","nombre":"Essential","precio":15},
  {"id":"p148","casa":"Lancôme","nombre":"Idôle","precio":9},
  {"id":"p149","casa":"Lancôme","nombre":"La Vie Est Belle","precio":15},
  {"id":"p150","casa":"Lancôme","nombre":"La Vie Est Belle Elixir","precio":15},
  {"id":"p151","casa":"Lattafa","nombre":"Art of Universe","precio":20},
  {"id":"p152","casa":"Lattafa","nombre":"Asad Bourbon","precio":15},
  {"id":"p153","casa":"Lattafa","nombre":"Asad Elixir","precio":20},
  {"id":"p154","casa":"Lattafa","nombre":"Asad (Original)","precio":15},
  {"id":"p155","casa":"Lattafa","nombre":"Asad Zanzibar","precio":15},
  {"id":"p156","casa":"Lattafa","nombre":"Bade\u0027e Al Oud Amethyst","precio":20},
  {"id":"p157","casa":"Lattafa","nombre":"Bade\u0027e Al Oud Honor \u0026 Glory","precio":20},
  {"id":"p158","casa":"Lattafa","nombre":"Bade\u0027e Al Oud Noble Blush","precio":20},
  {"id":"p159","casa":"Lattafa","nombre":"Bade\u0027e Al Oud Oud For Glory","precio":20},
  {"id":"p160","casa":"Lattafa","nombre":"Bade\u0027e Al Oud Sublime","precio":20},
  {"id":"p161","casa":"Lattafa","nombre":"Eclaire (Original)","precio":20},
  {"id":"p162","casa":"Lattafa","nombre":"Eclaire Banoffi","precio":20},
  {"id":"p163","casa":"Lattafa","nombre":"Eclaire Pistache","precio":20},
  {"id":"p164","casa":"Lattafa","nombre":"Emeer","precio":20},
  {"id":"p165","casa":"Lattafa","nombre":"Fakhar Lattafa Men","precio":20},
  {"id":"p166","casa":"Lattafa","nombre":"Fakhar Lattafa Women","precio":20},
  {"id":"p167","casa":"Lattafa","nombre":"Fakhar Lattafa Platin","precio":20},
  {"id":"p168","casa":"Lattafa","nombre":"Fakhar Lattafa Extrait","precio":20},
  {"id":"p169","casa":"Lattafa","nombre":"Give Me Gourmand Whipped Pleasure","precio":22},
  {"id":"p170","casa":"Lattafa","nombre":"Give Me Gourmand Mallow Madness","precio":22},
  {"id":"p171","casa":"Lattafa","nombre":"Give Me Gourmand Choco Overdose","precio":22},
  {"id":"p172","casa":"Lattafa","nombre":"Give Me Gourmand Cookie Crave","precio":22},
  {"id":"p173","casa":"Lattafa","nombre":"Give Me Gourmand Vanilla Freak","precio":22},
  {"id":"p174","casa":"Lattafa","nombre":"Give Me Gourmand Berrey On Top","precio":22},
  {"id":"p175","casa":"Lattafa","nombre":"Haya","precio":20},
  {"id":"p176","casa":"Lattafa","nombre":"Emaan","precio":20},
  {"id":"p177","casa":"Lattafa","nombre":"Sakeena","precio":20},
  {"id":"p178","casa":"Lattafa","nombre":"Sehr Lattafa","precio":20},
  {"id":"p179","casa":"Lattafa","nombre":"Her Confession","precio":20},
  {"id":"p180","casa":"Lattafa","nombre":"His Confession","precio":20},
  {"id":"p181","casa":"Lattafa","nombre":"Khamrah","precio":20},
  {"id":"p182","casa":"Lattafa","nombre":"Khamrah Dukhan","precio":20},
  {"id":"p183","casa":"Lattafa","nombre":"Khamrah Qahwa","precio":20},
  {"id":"p184","casa":"Lattafa","nombre":"Khamrah Waha","precio":20},
  {"id":"p185","casa":"Lattafa","nombre":"Mayar (Original)","precio":20},
  {"id":"p186","casa":"Lattafa","nombre":"Mayar Cherry","precio":20},
  {"id":"p187","casa":"Lattafa","nombre":"Mayar Natural Intense","precio":20},
  {"id":"p188","casa":"Lattafa","nombre":"Victoria Lattafa","precio":20},
  {"id":"p189","casa":"Lattafa","nombre":"Yara","precio":15},
  {"id":"p190","casa":"Lattafa","nombre":"Yara Candy","precio":15},
  {"id":"p191","casa":"Lattafa","nombre":"Yara Elixir","precio":20},
  {"id":"p192","casa":"Lattafa","nombre":"Yara Moi","precio":15},
  {"id":"p193","casa":"Lattafa","nombre":"Yara Tous","precio":15},
  {"id":"p194","casa":"Le Labo","nombre":"Santal 33","precio":20},
  {"id":"p195","casa":"Marc Jacobs","nombre":"Decadence","precio":9},
  {"id":"p196","casa":"Moschino","nombre":"Moschino Toy 2 (Blanco)","precio":15},
  {"id":"p197","casa":"Moschino","nombre":"Moschino Toy 2 Gum Rosado","precio":15},
  {"id":"p198","casa":"Nautica","nombre":"Voyage","precio":15},
  {"id":"p199","casa":"Orientica","nombre":"Amber Rouge","precio":20},
  {"id":"p200","casa":"Orientica","nombre":"Exclusive Dania","precio":20},
  {"id":"p201","casa":"Orientica","nombre":"Noble","precio":20},
  {"id":"p202","casa":"Orientica","nombre":"Royal Amber","precio":20},
  {"id":"p203","casa":"Orientica","nombre":"Royal Bleu","precio":20},
  {"id":"p204","casa":"Orientica","nombre":"Velvet Gold","precio":20},
  {"id":"p205","casa":"Orientica","nombre":"Oud Saffron","precio":20},
  {"id":"p206","casa":"Orientica","nombre":"Exclusive Azure Fantasy","precio":20},
  {"id":"p207","casa":"Paco Rabanne","nombre":"1 Million (Original)","precio":15},
  {"id":"p208","casa":"Paco Rabanne","nombre":"1 Million Elixir","precio":15},
  {"id":"p209","casa":"Paco Rabanne","nombre":"1 Million Lucky","precio":15},
  {"id":"p210","casa":"Paco Rabanne","nombre":"1 Million Royal","precio":15},
  {"id":"p211","casa":"Paco Rabanne","nombre":"Lady Million","precio":15},
  {"id":"p212","casa":"Paco Rabanne","nombre":"Lady Million Lucky","precio":15},
  {"id":"p213","casa":"Paco Rabanne","nombre":"Fame (Original)","precio":15},
  {"id":"p214","casa":"Paco Rabanne","nombre":"Fame Intense","precio":15},
  {"id":"p215","casa":"Paco Rabanne","nombre":"Fame Parfum","precio":15},
  {"id":"p216","casa":"Paco Rabanne","nombre":"Invictus","precio":15},
  {"id":"p217","casa":"Paco Rabanne","nombre":"Invictus Ónix","precio":15},
  {"id":"p218","casa":"Paco Rabanne","nombre":"Invictus Victory","precio":15},
  {"id":"p219","casa":"Paco Rabanne","nombre":"Invictus Victory Elixir","precio":15},
  {"id":"p220","casa":"Paco Rabanne","nombre":"Invictus Parfum","precio":15},
  {"id":"p221","casa":"Paco Rabanne","nombre":"Invictus Platinum","precio":15},
  {"id":"p222","casa":"Paco Rabanne","nombre":"Olympea Parfum","precio":15},
  {"id":"p223","casa":"Paco Rabanne","nombre":"Olympea","precio":15},
  {"id":"p224","casa":"Paco Rabanne","nombre":"Phantom","precio":20},
  {"id":"p225","casa":"Paco Rabanne","nombre":"Phantom Parfum","precio":20},
  {"id":"p226","casa":"Paco Rabanne","nombre":"Phantom Intense","precio":20},
  {"id":"p227","casa":"Parfums de Marly","nombre":"Layton","precio":20},
  {"id":"p228","casa":"Parfums de Marly","nombre":"Delina","precio":20},
  {"id":"p229","casa":"Paris Hilton","nombre":"Paris Hilton For Men","precio":15},
  {"id":"p230","casa":"Paris Hilton","nombre":"Paris Hilton For Women","precio":15},
  {"id":"p231","casa":"Paris Hilton","nombre":"Heiress by Paris Hilton","precio":15},
  {"id":"p232","casa":"Paris Hilton","nombre":"Can Can","precio":15},
  {"id":"p233","casa":"Perry Ellis","nombre":"360 For Men","precio":15},
  {"id":"p234","casa":"Perry Ellis","nombre":"360 Red","precio":15},
  {"id":"p235","casa":"Rasasi","nombre":"Hawas for Her","precio":20},
  {"id":"p236","casa":"Rasasi","nombre":"Hawas for Him","precio":20},
  {"id":"p237","casa":"Rasasi","nombre":"Hawas Ice","precio":20},
  {"id":"p238","casa":"Rasasi","nombre":"Hawas Fire","precio":20},
  {"id":"p239","casa":"Rasasi","nombre":"Hawas Elixir","precio":20},
  {"id":"p240","casa":"Rasasi","nombre":"Hawas Malibu","precio":20},
  {"id":"p241","casa":"Rasasi","nombre":"Hawas Black","precio":20},
  {"id":"p242","casa":"Rasasi","nombre":"Hawas Kobra","precio":20},
  {"id":"p243","casa":"Rave","nombre":"Now Woman Pink","precio":20},
  {"id":"p244","casa":"Saint Laurent","nombre":"Yves Saint Laurent","precio":18},
  {"id":"p245","casa":"Emper","nombre":"Stallion 53","precio":15},
  {"id":"p246","casa":"Tommy Hilfiger","nombre":"Tommy","precio":15},
  {"id":"p247","casa":"Tommy Hilfiger","nombre":"Tommy Girl","precio":15},
  {"id":"p248","casa":"Valentino","nombre":"Valentino Donna Born In Roma","precio":20},
  {"id":"p249","casa":"Valentino","nombre":"Valentino Donna Born In Roma Coral Fantasy","precio":20},
  {"id":"p250","casa":"Valentino","nombre":"Valentino Donna Born In Roma Yellow Dream","precio":20},
  {"id":"p251","casa":"Valentino","nombre":"Valentino Donna Born In Roma Ivory","precio":20},
  {"id":"p252","casa":"Valentino","nombre":"Valentino Uomo","precio":20},
  {"id":"p253","casa":"Valentino","nombre":"Valentino Uomo Born In Roma","precio":20},
  {"id":"p254","casa":"Versace","nombre":"Eros","precio":15},
  {"id":"p255","casa":"Versace","nombre":"Eros Energy","precio":15},
  {"id":"p256","casa":"Versace","nombre":"Eros Flame","precio":15},
  {"id":"p257","casa":"Victoria Secret","nombre":"Bombshell Intense","precio":9},
  {"id":"p258","casa":"Victorinox","nombre":"Swiss Army Classic","precio":15},
  {"id":"p259","casa":"Xerjoff","nombre":"Erba Pura","precio":20},
  {"id":"p260","casa":"Xerjoff","nombre":"Naxos","precio":20},
];

const STORAGE_CATALOGO_KEY = "aura_perfumes_catalogo";

function obtenerPerfumes() {
  try {
    const guardados = localStorage.getItem(STORAGE_CATALOGO_KEY);
    if (guardados) {
      const parsed = JSON.parse(guardados);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch (e) {}
  return PERFUMES_BASE.map(function(p) { return Object.assign({}, p); });
}

function guardarPerfumes(nuevaLista) {
  try {
    localStorage.setItem(STORAGE_CATALOGO_KEY, JSON.stringify(nuevaLista));
    return true;
  } catch (e) { return false; }
}

function restaurarPerfumesOriginales() {
  try {
    localStorage.removeItem(STORAGE_CATALOGO_KEY);
  } catch (e) {}
  return PERFUMES_BASE.map(function(p) { return Object.assign({}, p); });
}

// Exportar globalmente para navegador
if (typeof window !== "undefined") {
  window.PERFUMES_BASE = PERFUMES_BASE;
  window.obtenerPerfumes = obtenerPerfumes;
  window.guardarPerfumes = guardarPerfumes;
  window.restaurarPerfumesOriginales = restaurarPerfumesOriginales;
}
