/**
 * ====================================================================
 * CATÃLOGO DE PERFUMES (VENTA EXCLUSIVA AL DETAL)
 * ====================================================================
 * AquÃ­ tienes todos los artÃ­culos y sus precios unitarios al detal.
 * Puedes modificar los precios directamente en este archivo, o
 * usar el Panel de AdministraciÃ³n (admin.html) para cambiarlos visualmente.
 */

const PERFUMES_BASE = [
  { id: 'p001', casa: 'Afnan', nombre: '9 AM Dive', precio: 25 },
  { id: 'p002', casa: 'Afnan', nombre: '9 AM Pour Femme', precio: 25 },
  { id: 'p003', casa: 'Afnan', nombre: '9 PM Elixir', precio: 25 },
  { id: 'p004', casa: 'Afnan', nombre: '9 PM Men', precio: 25 },
  { id: 'p005', casa: 'Afnan', nombre: '9 PM Night Out', precio: 30 },
  { id: 'p006', casa: 'Afnan', nombre: '9 PM Pour Femme', precio: 25 },
  { id: 'p007', casa: 'Afnan', nombre: '9 PM Rebel', precio: 25 },
  { id: 'p008', casa: 'Al Haramain', nombre: 'Amber Oud Aqua Dubai Edition', precio: 25 },
  { id: 'p009', casa: 'Al Haramain', nombre: 'Amber Oud Dubai Night', precio: 25 },
  { id: 'p010', casa: 'Al Haramain', nombre: 'Amber Oud Gold Edition', precio: 25 },
  { id: 'p011', casa: 'Al Haramain', nombre: 'Amber Oud Ultra Violet', precio: 25 },
  { id: 'p012', casa: 'Antonio Banderas', nombre: 'Blue Seduction', precio: 23 },
  { id: 'p013', casa: 'Ariana Grande', nombre: 'Ari', precio: 23 },
  { id: 'p014', casa: 'Ariana Grande', nombre: 'Cloud', precio: 14 },
  { id: 'p015', casa: 'Ariana Grande', nombre: 'Cloud Intense', precio: 14 },
  { id: 'p016', casa: 'Ariana Grande', nombre: 'Cloud Pink', precio: 20 },
  { id: 'p017', casa: 'Ariana Grande', nombre: 'Mod', precio: 20 },
  { id: 'p018', casa: 'Ariana Grande', nombre: 'Mod Blush', precio: 20 },
  { id: 'p019', casa: 'Ariana Grande', nombre: 'REM', precio: 23 },
  { id: 'p020', casa: 'Ariana Grande', nombre: 'Sweet Like Candy', precio: 23 },
  { id: 'p021', casa: 'Ariana Grande', nombre: 'Thank U Next', precio: 20 },
  { id: 'p022', casa: 'Ariana Grande', nombre: 'Thank U Next 2.0', precio: 20 },
  { id: 'p023', casa: 'Armaf', nombre: 'Caballo', precio: 25 },
  { id: 'p024', casa: 'Armaf', nombre: 'Club de Nuit Intense Man', precio: 20 },
  { id: 'p025', casa: 'Armaf', nombre: 'Club de Nuit Lionheart Men', precio: 25 },
  { id: 'p026', casa: 'Armaf', nombre: 'Club de Nuit Lionheart Woman', precio: 25 },
  { id: 'p027', casa: 'Armaf', nombre: 'Club de Nuit Oud', precio: 20 },
  { id: 'p028', casa: 'Armaf', nombre: 'Club de Nuit Milestone', precio: 20 },
  { id: 'p029', casa: 'Armaf', nombre: 'Club de Nuit Imperiale', precio: 20 },
  { id: 'p030', casa: 'Armaf', nombre: 'Club de Nuit Sillage', precio: 20 },
  { id: 'p031', casa: 'Armaf', nombre: 'Club de Nuit Untold', precio: 20 },
  { id: 'p032', casa: 'Armaf', nombre: 'Club de Nuit Maleka', precio: 20 },
  { id: 'p033', casa: 'Armaf', nombre: 'Club de Nuit Iconic', precio: 20 },
  { id: 'p034', casa: 'Armaf', nombre: 'Club de Nuit Urban Man Elixir', precio: 20 },
  { id: 'p035', casa: 'Armaf', nombre: 'Club de Nuit Woman', precio: 20 },
  { id: 'p036', casa: 'Armaf', nombre: 'Club de Nuit Precieux', precio: 35 },
  { id: 'p037', casa: 'Armaf', nombre: 'Island Bliss', precio: 25 },
  { id: 'p038', casa: 'Armaf', nombre: 'Island Breeze', precio: 25 },
  { id: 'p039', casa: 'Armaf', nombre: 'Bon Bon', precio: 25 },
  { id: 'p040', casa: 'Armaf', nombre: 'Odyssey AOUD', precio: 20 },
  { id: 'p041', casa: 'Armaf', nombre: 'Odyssey Aqua', precio: 25 },
  { id: 'p042', casa: 'Armaf', nombre: 'Odyssey Artisto', precio: 20 },
  { id: 'p043', casa: 'Armaf', nombre: 'Odyssey Bahamas', precio: 25 },
  { id: 'p044', casa: 'Armaf', nombre: 'Odyssey Candee', precio: 20 },
  { id: 'p045', casa: 'Armaf', nombre: 'Odyssey Dubai Chocolate', precio: 25 },
  { id: 'p046', casa: 'Armaf', nombre: 'Odyssey Homme', precio: 20 },
  { id: 'p047', casa: 'Armaf', nombre: 'Odyssey Homme White Edition', precio: 20 },
  { id: 'p048', casa: 'Armaf', nombre: 'Odyssey Limoni', precio: 25 },
  { id: 'p049', casa: 'Armaf', nombre: 'Odyssey Mandarin Sky', precio: 25 },
  { id: 'p050', casa: 'Armaf', nombre: 'Odyssey Mandarin Sky Elixir', precio: 25 },
  { id: 'p051', casa: 'Armaf', nombre: 'Odyssey Mandarin Sky Vintage', precio: 25 },
  { id: 'p052', casa: 'Armaf', nombre: 'Odyssey Marshmellow', precio: 25 },
  { id: 'p053', casa: 'Armaf', nombre: 'Odyssey Mega', precio: 20 },
  { id: 'p054', casa: 'Armaf', nombre: 'Odyssey Go Mango', precio: 25 },
  { id: 'p055', casa: 'Armaf', nombre: 'Odyssey Toffee Coffee', precio: 25 },
  { id: 'p056', casa: 'Armaf', nombre: 'Odyssey Spectra', precio: 20 },
  { id: 'p057', casa: 'Armaf', nombre: 'Odyssey Eau de Montagne', precio: 25 },
  { id: 'p058', casa: 'Armaf', nombre: 'Odyssey Tyrant', precio: 20 },
  { id: 'p059', casa: 'Armaf', nombre: 'Odyssey Wild One', precio: 20 },
  { id: 'p060', casa: 'Armaf', nombre: 'Yum Yum', precio: 25 },
  { id: 'p061', casa: 'Azzaro', nombre: 'Azzaro Wanted', precio: 25 },
  { id: 'p062', casa: 'Azzaro', nombre: 'Azzaro Intense', precio: 25 },
  { id: 'p063', casa: 'Bharara', nombre: 'Double Bleu', precio: 25 },
  { id: 'p064', casa: 'Bharara', nombre: 'King', precio: 25 },
  { id: 'p065', casa: 'Bharara', nombre: 'Niche Femme', precio: 25 },
  { id: 'p066', casa: 'Bharara', nombre: 'Onyx', precio: 25 },
  { id: 'p067', casa: 'Bharara', nombre: 'Rose', precio: 25 },
  { id: 'p068', casa: 'Bharara', nombre: 'Scarlett', precio: 25 },
  { id: 'p069', casa: 'Bharara', nombre: 'Soleil', precio: 25 },
  { id: 'p070', casa: 'Britney Spears', nombre: 'Fantasy', precio: 20 },
  { id: 'p071', casa: 'Britney Spears', nombre: 'Fantasy Anniversary', precio: 20 },
  { id: 'p072', casa: 'Britney Spears', nombre: 'Fantasy Midnight', precio: 20 },
  { id: 'p073', casa: 'Calvin Klein', nombre: 'Eternity', precio: 20 },
  { id: 'p074', casa: 'Calvin Klein', nombre: 'One', precio: 20 },
  { id: 'p075', casa: 'Carolina Herrera', nombre: '212 HÃ©roes Forever Young W', precio: 20 },
  { id: 'p076', casa: 'Carolina Herrera', nombre: '212 Men Heroes Forever Young', precio: 20 },
  { id: 'p077', casa: 'Carolina Herrera', nombre: '212 Men NYC', precio: 20 },
  { id: 'p078', casa: 'Carolina Herrera', nombre: '212 VIP Black', precio: 20 },
  { id: 'p079', casa: 'Carolina Herrera', nombre: '212 VIP Black I Love NY', precio: 20 },
  { id: 'p080', casa: 'Carolina Herrera', nombre: '212 VIP Men', precio: 20 },
  { id: 'p081', casa: 'Carolina Herrera', nombre: '212 VIP RosÃ©', precio: 20 },
  { id: 'p082', casa: 'Carolina Herrera', nombre: '212 VIP RosÃ© NY', precio: 20 },
  { id: 'p083', casa: 'Carolina Herrera', nombre: 'Bad Boy', precio: 20 },
  { id: 'p084', casa: 'Carolina Herrera', nombre: 'CH', precio: 20 },
  { id: 'p085', casa: 'Carolina Herrera', nombre: 'Good Girl', precio: 20 },
  { id: 'p086', casa: 'Carolina Herrera', nombre: 'Good Girl Blush', precio: 25 },
  { id: 'p087', casa: 'Carolina Herrera', nombre: 'Good Girl Gold Fantasy', precio: 20 },
  { id: 'p088', casa: 'Carolina Herrera', nombre: 'Good Girl Fantastic Pink', precio: 25 },
  { id: 'p089', casa: 'Carolina Herrera', nombre: 'Good Girl Blush Elixir', precio: 25 },
  { id: 'p090', casa: 'Carolina Herrera', nombre: 'Good Girl Velvet Fatale', precio: 20 },
  { id: 'p091', casa: 'Carolina Herrera', nombre: 'La Bomba', precio: 25 },
  { id: 'p092', casa: 'Carolina Herrera', nombre: 'Very Good Girl', precio: 20 },
  { id: 'p093', casa: 'Chanel', nombre: 'Allure Homme Sport', precio: 20 },
  { id: 'p094', casa: 'Chanel', nombre: 'Bleu de Chanel', precio: 20 },
  { id: 'p095', casa: 'Chanel', nombre: 'Chance Eau Tendre', precio: 20 },
  { id: 'p096', casa: 'Chanel', nombre: 'Chanel No.5', precio: 20 },
  { id: 'p097', casa: 'Chanel', nombre: 'Coco Mademoiselle', precio: 20 },
  { id: 'p098', casa: 'Christian Dior', nombre: 'Miss Dior', precio: 25 },
  { id: 'p099', casa: 'Christian Dior', nombre: 'Sauvage', precio: 23 },
  { id: 'p100', casa: 'Christian Dior', nombre: 'Sauvage Elixir', precio: 23 },
  { id: 'p101', casa: 'Creed', nombre: 'Creed Aventus', precio: 20 },
  { id: 'p102', casa: 'Creed', nombre: 'Creed Silver Mountain Water', precio: 20 },
  { id: 'p103', casa: 'Creed', nombre: 'Creed Absolu Aventus', precio: 20 },
  { id: 'p104', casa: 'Dolce & Gabbana', nombre: 'Light Blue Pour Femme', precio: 20 },
  { id: 'p105', casa: 'Dolce & Gabbana', nombre: 'Light Blue Pour Homme', precio: 20 },
  { id: 'p106', casa: 'Dolce & Gabbana', nombre: 'Light Blue Love is Love W', precio: 20 },
  { id: 'p107', casa: 'Dumont', nombre: 'Nitro Red', precio: 25 },
  { id: 'p108', casa: 'Escada', nombre: 'Fairy Love', precio: 14 },
  { id: 'p109', casa: 'Escada', nombre: 'Sorbetto Rosso', precio: 20 },
  { id: 'p110', casa: 'Ferrari', nombre: 'Scuderia Ferrari Red', precio: 20 },
  { id: 'p111', casa: 'French Avenue', nombre: 'Vulcan Baie', precio: 25 },
  { id: 'p112', casa: 'French Avenue', nombre: 'Vulcan Feu', precio: 25 },
  { id: 'p113', casa: 'French Avenue', nombre: 'Vulcan Sable', precio: 25 },
  { id: 'p114', casa: 'Giorgio Armani', nombre: 'Acqua Di Gio (Normal)', precio: 20 },
  { id: 'p115', casa: 'Giorgio Armani', nombre: 'Acqua Di Gio Profumo', precio: 20 },
  { id: 'p116', casa: 'Giorgio Armani', nombre: 'Stronger With You', precio: 25 },
  { id: 'p117', casa: 'Giorgio Armani', nombre: 'Stronger With You Intensely', precio: 25 },
  { id: 'p118', casa: 'Givenchy', nombre: 'Pour Homme', precio: 20 },
  { id: 'p119', casa: 'Hugo Boss', nombre: 'Man', precio: 20 },
  { id: 'p120', casa: 'Hugo Boss', nombre: 'Intense', precio: 20 },
  { id: 'p121', casa: 'Hugo Boss', nombre: 'Jeans', precio: 20 },
  { id: 'p122', casa: 'Hugo Boss', nombre: 'Boss Bottled', precio: 20 },
  { id: 'p123', casa: 'Hugo Boss', nombre: 'Boss Bottled Infinite', precio: 20 },
  { id: 'p124', casa: 'Hugo Boss', nombre: 'Boss Bottled Night', precio: 20 },
  { id: 'p125', casa: 'Hugo Boss', nombre: 'Boss Bottled Marine', precio: 20 },
  { id: 'p126', casa: 'Hugo Boss', nombre: 'Boss Unlimited', precio: 20 },
  { id: 'p127', casa: 'Hugo Boss', nombre: 'Boss Bottled Absolu', precio: 20 },
  { id: 'p128', casa: 'Hugo Boss', nombre: 'Hugo Boss Parfum', precio: 20 },
  { id: 'p129', casa: 'Hugo Boss', nombre: 'The Scent Woman', precio: 14 },
  { id: 'p130', casa: 'Issey Miyake', nombre: 'L'eau D'issey pour Homme', precio: 20 },
  { id: 'p131', casa: 'Jean Paul Gaultier', nombre: 'Gaultier Divine', precio: 25 },
  { id: 'p132', casa: 'Jean Paul Gaultier', nombre: 'La Belle Paradise Garden', precio: 25 },
  { id: 'p133', casa: 'Jean Paul Gaultier', nombre: 'Le Male', precio: 25 },
  { id: 'p134', casa: 'Jean Paul Gaultier', nombre: 'Le Male Aviator', precio: 25 },
  { id: 'p135', casa: 'Jean Paul Gaultier', nombre: 'Le Male Le Parfum', precio: 25 },
  { id: 'p136', casa: 'Jean Paul Gaultier', nombre: 'Le Beau', precio: 25 },
  { id: 'p137', casa: 'Jean Paul Gaultier', nombre: 'Le Beau Le Parfum', precio: 25 },
  { id: 'p138', casa: 'Jean Paul Gaultier', nombre: 'Le Beau Paradise Garden', precio: 25 },
  { id: 'p139', casa: 'Jean Paul Gaultier', nombre: 'Le Male Elixir', precio: 25 },
  { id: 'p140', casa: 'Jean Paul Gaultier', nombre: 'Scandal Pour Femme', precio: 25 },
  { id: 'p141', casa: 'Jean Paul Gaultier', nombre: 'Scandal Pour Homme', precio: 25 },
  { id: 'p142', casa: 'Jean Paul Gaultier', nombre: 'Scandal Intense', precio: 25 },
  { id: 'p143', casa: 'Jean Paul Gaultier', nombre: 'Scandal Le Parfum', precio: 25 },
  { id: 'p144', casa: 'Jean Paul Gaultier', nombre: 'Ultra Male', precio: 25 },
  { id: 'p145', casa: 'Katy Perry', nombre: 'Purr', precio: 20 },
  { id: 'p146', casa: 'Katy Perry', nombre: 'Meow', precio: 20 },
  { id: 'p147', casa: 'Lacoste', nombre: 'Essential', precio: 20 },
  { id: 'p148', casa: 'LancÃ´me', nombre: 'IdÃ´le', precio: 14 },
  { id: 'p149', casa: 'LancÃ´me', nombre: 'La Vie Est Belle', precio: 20 },
  { id: 'p150', casa: 'LancÃ´me', nombre: 'La Vie Est Belle Elixir', precio: 20 },
  { id: 'p151', casa: 'Lattafa', nombre: 'Art of Universe', precio: 25 },
  { id: 'p152', casa: 'Lattafa', nombre: 'Asad Bourbon', precio: 20 },
  { id: 'p153', casa: 'Lattafa', nombre: 'Asad Elixir', precio: 25 },
  { id: 'p154', casa: 'Lattafa', nombre: 'Asad (Original)', precio: 20 },
  { id: 'p155', casa: 'Lattafa', nombre: 'Asad Zanzibar', precio: 20 },
  { id: 'p156', casa: 'Lattafa', nombre: 'Bade'e Al Oud Amethyst', precio: 25 },
  { id: 'p157', casa: 'Lattafa', nombre: 'Bade'e Al Oud Honor & Glory', precio: 25 },
  { id: 'p158', casa: 'Lattafa', nombre: 'Bade'e Al Oud Noble Blush', precio: 25 },
  { id: 'p159', casa: 'Lattafa', nombre: 'Bade'e Al Oud Oud For Glory', precio: 25 },
  { id: 'p160', casa: 'Lattafa', nombre: 'Bade'e Al Oud Sublime', precio: 25 },
  { id: 'p161', casa: 'Lattafa', nombre: 'Eclaire (Original)', precio: 25 },
  { id: 'p162', casa: 'Lattafa', nombre: 'Eclaire Banoffi', precio: 25 },
  { id: 'p163', casa: 'Lattafa', nombre: 'Eclaire Pistache', precio: 25 },
  { id: 'p164', casa: 'Lattafa', nombre: 'Emeer', precio: 25 },
  { id: 'p165', casa: 'Lattafa', nombre: 'Fakhar Lattafa Men', precio: 25 },
  { id: 'p166', casa: 'Lattafa', nombre: 'Fakhar Lattafa Women', precio: 25 },
  { id: 'p167', casa: 'Lattafa', nombre: 'Fakhar Lattafa Platin', precio: 25 },
  { id: 'p168', casa: 'Lattafa', nombre: 'Fakhar Lattafa Extrait', precio: 25 },
  { id: 'p169', casa: 'Lattafa', nombre: 'Give Me Gourmand Whipped Pleasure', precio: 27 },
  { id: 'p170', casa: 'Lattafa', nombre: 'Give Me Gourmand Mallow Madness', precio: 27 },
  { id: 'p171', casa: 'Lattafa', nombre: 'Give Me Gourmand Choco Overdose', precio: 27 },
  { id: 'p172', casa: 'Lattafa', nombre: 'Give Me Gourmand Cookie Crave', precio: 27 },
  { id: 'p173', casa: 'Lattafa', nombre: 'Give Me Gourmand Vanilla Freak', precio: 27 },
  { id: 'p174', casa: 'Lattafa', nombre: 'Give Me Gourmand Berrey On Top', precio: 27 },
  { id: 'p175', casa: 'Lattafa', nombre: 'Haya', precio: 25 },
  { id: 'p176', casa: 'Lattafa', nombre: 'Emaan', precio: 25 },
  { id: 'p177', casa: 'Lattafa', nombre: 'Sakeena', precio: 25 },
  { id: 'p178', casa: 'Lattafa', nombre: 'Sehr Lattafa', precio: 25 },
  { id: 'p179', casa: 'Lattafa', nombre: 'Her Confession', precio: 25 },
  { id: 'p180', casa: 'Lattafa', nombre: 'His Confession', precio: 25 },
  { id: 'p181', casa: 'Lattafa', nombre: 'Khamrah', precio: 25 },
  { id: 'p182', casa: 'Lattafa', nombre: 'Khamrah Dukhan', precio: 25 },
  { id: 'p183', casa: 'Lattafa', nombre: 'Khamrah Qahwa', precio: 25 },
  { id: 'p184', casa: 'Lattafa', nombre: 'Khamrah Waha', precio: 25 },
  { id: 'p185', casa: 'Lattafa', nombre: 'Mayar (Original)', precio: 25 },
  { id: 'p186', casa: 'Lattafa', nombre: 'Mayar Cherry', precio: 25 },
  { id: 'p187', casa: 'Lattafa', nombre: 'Mayar Natural Intense', precio: 25 },
  { id: 'p188', casa: 'Lattafa', nombre: 'Victoria Lattafa', precio: 25 },
  { id: 'p189', casa: 'Lattafa', nombre: 'Yara', precio: 20 },
  { id: 'p190', casa: 'Lattafa', nombre: 'Yara Candy', precio: 20 },
  { id: 'p191', casa: 'Lattafa', nombre: 'Yara Elixir', precio: 25 },
  { id: 'p192', casa: 'Lattafa', nombre: 'Yara Moi', precio: 20 },
  { id: 'p193', casa: 'Lattafa', nombre: 'Yara Tous', precio: 20 },
  { id: 'p194', casa: 'Le Labo', nombre: 'Santal 33', precio: 25 },
  { id: 'p195', casa: 'Marc Jacobs', nombre: 'Decadence', precio: 14 },
  { id: 'p196', casa: 'Moschino', nombre: 'Moschino Toy 2 (Blanco)', precio: 20 },
  { id: 'p197', casa: 'Moschino', nombre: 'Moschino Toy 2 Gum Rosado', precio: 20 },
  { id: 'p198', casa: 'Nautica', nombre: 'Voyage', precio: 20 },
  { id: 'p199', casa: 'Orientica', nombre: 'Amber Rouge', precio: 25 },
  { id: 'p200', casa: 'Orientica', nombre: 'Exclusive Dania', precio: 25 },
  { id: 'p201', casa: 'Orientica', nombre: 'Noble', precio: 25 },
  { id: 'p202', casa: 'Orientica', nombre: 'Royal Amber', precio: 25 },
  { id: 'p203', casa: 'Orientica', nombre: 'Royal Bleu', precio: 25 },
  { id: 'p204', casa: 'Orientica', nombre: 'Velvet Gold', precio: 25 },
  { id: 'p205', casa: 'Orientica', nombre: 'Oud Saffron', precio: 25 },
  { id: 'p206', casa: 'Orientica', nombre: 'Exclusive Azure Fantasy', precio: 25 },
  { id: 'p207', casa: 'Paco Rabanne', nombre: '1 Million (Original)', precio: 20 },
  { id: 'p208', casa: 'Paco Rabanne', nombre: '1 Million Elixir', precio: 20 },
  { id: 'p209', casa: 'Paco Rabanne', nombre: '1 Million Lucky', precio: 20 },
  { id: 'p210', casa: 'Paco Rabanne', nombre: '1 Million Royal', precio: 20 },
  { id: 'p211', casa: 'Paco Rabanne', nombre: 'Lady Million', precio: 20 },
  { id: 'p212', casa: 'Paco Rabanne', nombre: 'Lady Million Lucky', precio: 20 },
  { id: 'p213', casa: 'Paco Rabanne', nombre: 'Fame (Original)', precio: 20 },
  { id: 'p214', casa: 'Paco Rabanne', nombre: 'Fame Intense', precio: 20 },
  { id: 'p215', casa: 'Paco Rabanne', nombre: 'Fame Parfum', precio: 20 },
  { id: 'p216', casa: 'Paco Rabanne', nombre: 'Invictus', precio: 20 },
  { id: 'p217', casa: 'Paco Rabanne', nombre: 'Invictus Ã“nix', precio: 20 },
  { id: 'p218', casa: 'Paco Rabanne', nombre: 'Invictus Victory', precio: 20 },
  { id: 'p219', casa: 'Paco Rabanne', nombre: 'Invictus Victory Elixir', precio: 20 },
  { id: 'p220', casa: 'Paco Rabanne', nombre: 'Invictus Parfum', precio: 20 },
  { id: 'p221', casa: 'Paco Rabanne', nombre: 'Invictus Platinum', precio: 20 },
  { id: 'p222', casa: 'Paco Rabanne', nombre: 'Olympea Parfum', precio: 20 },
  { id: 'p223', casa: 'Paco Rabanne', nombre: 'Olympea', precio: 20 },
  { id: 'p224', casa: 'Paco Rabanne', nombre: 'Phantom', precio: 25 },
  { id: 'p225', casa: 'Paco Rabanne', nombre: 'Phantom Parfum', precio: 25 },
  { id: 'p226', casa: 'Paco Rabanne', nombre: 'Phantom Intense', precio: 25 },
  { id: 'p227', casa: 'Parfums de Marly', nombre: 'Layton', precio: 25 },
  { id: 'p228', casa: 'Parfums de Marly', nombre: 'Delina', precio: 25 },
  { id: 'p229', casa: 'Paris Hilton', nombre: 'Paris Hilton For Men', precio: 20 },
  { id: 'p230', casa: 'Paris Hilton', nombre: 'Paris Hilton For Women', precio: 20 },
  { id: 'p231', casa: 'Paris Hilton', nombre: 'Heiress by Paris Hilton', precio: 20 },
  { id: 'p232', casa: 'Paris Hilton', nombre: 'Can Can', precio: 20 },
  { id: 'p233', casa: 'Perry Ellis', nombre: '360 For Men', precio: 20 },
  { id: 'p234', casa: 'Perry Ellis', nombre: '360 Red', precio: 20 },
  { id: 'p235', casa: 'Rasasi', nombre: 'Hawas for Her', precio: 25 },
  { id: 'p236', casa: 'Rasasi', nombre: 'Hawas for Him', precio: 25 },
  { id: 'p237', casa: 'Rasasi', nombre: 'Hawas Ice', precio: 25 },
  { id: 'p238', casa: 'Rasasi', nombre: 'Hawas Fire', precio: 25 },
  { id: 'p239', casa: 'Rasasi', nombre: 'Hawas Elixir', precio: 25 },
  { id: 'p240', casa: 'Rasasi', nombre: 'Hawas Malibu', precio: 25 },
  { id: 'p241', casa: 'Rasasi', nombre: 'Hawas Black', precio: 25 },
  { id: 'p242', casa: 'Rasasi', nombre: 'Hawas Kobra', precio: 25 },
  { id: 'p243', casa: 'Rave', nombre: 'Now Woman Pink', precio: 25 },
  { id: 'p244', casa: 'Saint Laurent', nombre: 'Yves Saint Laurent', precio: 23 },
  { id: 'p245', casa: 'Emper', nombre: 'Stallion 53', precio: 20 },
  { id: 'p246', casa: 'Tommy Hilfiger', nombre: 'Tommy', precio: 20 },
  { id: 'p247', casa: 'Tommy Hilfiger', nombre: 'Tommy Girl', precio: 20 },
  { id: 'p248', casa: 'Valentino', nombre: 'Valentino Donna Born In Roma', precio: 25 },
  { id: 'p249', casa: 'Valentino', nombre: 'Valentino Donna Born In Roma Coral Fantasy', precio: 25 },
  { id: 'p250', casa: 'Valentino', nombre: 'Valentino Donna Born In Roma Yellow Dream', precio: 25 },
  { id: 'p251', casa: 'Valentino', nombre: 'Valentino Donna Born In Roma Ivory', precio: 25 },
  { id: 'p252', casa: 'Valentino', nombre: 'Valentino Uomo', precio: 25 },
  { id: 'p253', casa: 'Valentino', nombre: 'Valentino Uomo Born In Roma', precio: 25 },
  { id: 'p254', casa: 'Versace', nombre: 'Eros', precio: 20 },
  { id: 'p255', casa: 'Versace', nombre: 'Eros Energy', precio: 20 },
  { id: 'p256', casa: 'Versace', nombre: 'Eros Flame', precio: 20 },
  { id: 'p257', casa: 'Victoria Secret', nombre: 'Bombshell Intense', precio: 14 },
  { id: 'p258', casa: 'Victorinox', nombre: 'Swiss Army Classic', precio: 20 },
  { id: 'p259', casa: 'Xerjoff', nombre: 'Erba Pura', precio: 25 },
  { id: 'p260', casa: 'Xerjoff', nombre: 'Naxos', precio: 25 },
];


const STORAGE_CATALOGO_KEY = "aura_perfumes_catalogo";

/**
 * Obtiene la lista actual de perfumes (desde LocalStorage si fueron editados,
 * o la lista base por defecto).
 */
function obtenerPerfumes() {
  try {
    const guardados = localStorage.getItem(STORAGE_CATALOGO_KEY);
    if (guardados) {
      const parsed = JSON.parse(guardados);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch (e) {
    console.warn("No se pudo cargar desde LocalStorage, usando catÃ¡logo base:", e);
  }
  return PERFUMES_BASE.map(function(p) { return Object.assign({}, p); });
}

/**
 * Guarda los perfumes actualizados en LocalStorage para que se reflejen
 * de inmediato en toda la tienda.
 */
function guardarPerfumes(nuevaLista) {
  try {
    localStorage.setItem(STORAGE_CATALOGO_KEY, JSON.stringify(nuevaLista));
    return true;
  } catch (e) {
    console.error("Error al guardar perfumes en LocalStorage:", e);
    return false;
  }
}

/**
 * Restaura el catÃ¡logo a los precios y productos originales.
 */
function restaurarPerfumesOriginales() {
  localStorage.removeItem(STORAGE_CATALOGO_KEY);
  return PERFUMES_BASE.map(function(p) { return Object.assign({}, p); });
}
